# Generated by Django 5.2.7 on 2025-10-27 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FindItApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='phone',
            new_name='contact_number',
        ),
    ]
