# Generated by Django 5.2.7 on 2025-10-30 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FindItApp', '0002_rename_phone_item_contact_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='is_read',
            new_name='read',
        ),
    ]
