# Generated by Django 5.2.7 on 2025-10-30 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FindItApp', '0003_rename_is_read_notification_read'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='read',
            new_name='is_read',
        ),
    ]
